Installing the python datasets package

In [1]:
! pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.6 MB/s eta 0:00:00


Using the BERT model from the original from the Attention is All You Need paper. Know how to differentiate between lower and uppercase characters

In [3]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizing sentence

In [4]:
encoded = tokenizer.encode("The way to get started is to quit talking and begin doing")

In [5]:
print(tokenizer.convert_ids_to_tokens(encoded))

['[CLS]', 'the', 'way', 'to', 'get', 'started', 'is', 'to', 'quit', 'talking', 'and', 'begin', 'doing', '[SEP]']


In [6]:
print(encoded)

[101, 1996, 2126, 2000, 2131, 2318, 2003, 2000, 8046, 3331, 1998, 4088, 2725, 102]


In [7]:
encoded_input = tokenizer("Rose rose to put rose roses on her roses' rows")
print(encoded_input.keys())
print(encoded_input['input_ids'])

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
[101, 3123, 3123, 2000, 2404, 3123, 10529, 2006, 2014, 10529, 1005, 10281, 102]


In [2]:
! pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 621.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.0 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=2263cf00d189a2c78d76de5103e34964178ae1df03a78c53c539ef3b08b3e3fd
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [12]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
sentences = [
    "Rose rose to put rose roses on her roses' rows",
    "That that is is that that is not is not is that it it is.",
    "The bears bear hard hard yarn yarns."
]
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences,embeddings):
  print("###############################################################\n###############################################################")
  print("")

  print("Sentence:", sentence)
  print("Embedding:", embedding)
  print("")

###############################################################
###############################################################

Sentence: Rose rose to put rose roses on her roses' rows
Embedding: [-5.06095067e-02  3.74751864e-03  6.74413331e-03 -4.55798917e-02
 -7.41804019e-02  8.81632343e-02 -3.03165391e-02 -6.34983182e-03
  7.59276049e-03 -2.09231228e-02 -3.96484062e-02  5.87916747e-02
  1.81833971e-02 -2.53834445e-02 -3.13211083e-02  8.32581148e-02
 -6.54643849e-02  3.21451090e-02 -3.34185250e-02  1.43160345e-02
 -5.16963331e-03 -1.49589274e-02 -7.95862917e-03 -5.16050160e-02
 -1.97074730e-02  7.68656358e-02  1.07986964e-02  5.04852980e-02
 -2.92258579e-02 -3.08692083e-02  6.35013357e-02  2.72971708e-02
 -1.63952578e-02  5.92372566e-02 -4.07407135e-02  5.02681034e-03
 -3.58148701e-02 -5.26667014e-02  6.43852875e-02  6.10185154e-02
  2.20496431e-02 -1.13695957e-01  3.19551043e-02  8.81949905e-03
  3.21389511e-02 -3.76644768e-02  8.35762173e-02 -5.53594204e-03
 -1.76021084e-02 -2.588

Exploring the vector representation (the "embedding") of any sentence. Looking at teh tokenized form, the list of token_ids integers, or compute cosine similarities between the embeddings

In [13]:
words = ["turtle","slow", "gentle", "purple", "red"]
single_word_embeddings = model.encode(words)

for word, embed in zip(words, single_word_embeddings):
  print("word: ",word)
  print("embed: ", embed[0:10])
  print("")

word:  turtle
embed:  [-0.049017    0.09007166  0.00023625  0.02901489 -0.00428016 -0.0769367
  0.11347707 -0.00626967  0.02950992  0.02328188]

word:  slow
embed:  [-0.00731684 -0.0258791  -0.02762271  0.01204709  0.01932792 -0.08109292
 -0.01594131 -0.0421554   0.0605601  -0.0208003 ]

word:  gentle
embed:  [ 0.02598753  0.01464723  0.03668542  0.04263355 -0.02016317 -0.0370698
  0.00057896 -0.01800381 -0.01603301 -0.00273873]

word:  purple
embed:  [-0.05761681 -0.04419539 -0.07217059 -0.03221674 -0.01123551  0.00495188
  0.21028227 -0.03529096  0.04633704 -0.02883166]

word:  red
embed:  [-0.02509157  0.00884631 -0.10083686  0.01320893  0.01490392  0.02841406
  0.15962423  0.01331033  0.03514298 -0.04301142]



In [14]:
# python code to compute the matrix of cosines between all of the pairs of words in the list above
from sklearn.metrics.pairwise import cosine_similarity
word_embeddings = model.encode(words)
word_similarities = cosine_similarity(word_embeddings)
print(word_similarities)

[[0.99999964 0.32947138 0.23441619 0.4052983  0.36687693]
 [0.32947138 1.         0.37207317 0.30516243 0.33104777]
 [0.23441619 0.37207317 1.0000002  0.23564653 0.25393113]
 [0.4052983  0.30516243 0.23564653 0.9999999  0.66838574]
 [0.36687693 0.33104777 0.25393113 0.66838574 1.0000002 ]]


In [18]:
from scipy.spatial.distance import cosine
for key, sentence in enumerate(sentences):
  print(f"Sentence {key+1}: ", sentence)
print("")
print("Cosine similarity between the first two sentences:", cosine(embeddings[0], embeddings[1]))
print("Cosine similarity between the second and third sentences:", cosine(embeddings[1],embeddings[2]))
print("Cosine similarity between the first and third sentences:",cosine(embeddings[0],embeddings[2]))

Sentence 1:  Rose rose to put rose roses on her roses' rows
Sentence 2:  That that is is that that is not is not is that it it is.
Sentence 3:  The bears bear hard hard yarn yarns.

Cosine similarity between the first two sentences: 0.9985606279224157
Cosine similarity between the second and third sentences: 1.0282625947147608
Cosine similarity between the first and third sentences: 0.9291618689894676


Assignment 1
- Pull in the bert-base-uncased model, use it to generate embeddings for some text, and compare the embeddings to each other via cosine similarity (or euclidean distance)

- Pick a sentence with one or more words with multiple meanings (depending on context), like “flies” (could mean the plural - the insect -  or could be the verb “to fly”), and compute the contextual BERT embeddings for all the the words in the sentence.

- Pick another sentence, with one or more of those ambiguous words but with another meaning, and generate the contextual BERT embeddings for the words in that sentence.  Compare and contrast contextual embedding vectors of words which have changed meaning and those whose meaning has stayed the same.


NB: this code does the embedding for whole sentence instead of individual words.
The next block of code does it rightly.

In [8]:
from scipy.spatial.distance import cosine
from sentence_transformers import SentenceTransformer

# Initialize the model with bert-base-uncased
model = SentenceTransformer('bert-base-uncased')

# Define sentences with words that have multiple meanings
sentence1 = "She catches flies using a net."
sentence2 = "Time flies when you're having fun."

# Generate embeddings for the sentences
embeddings1 = model.encode([sentence1])
embeddings2 = model.encode([sentence2])

# Extract embeddings for all words in each sentence
words1 = sentence1.split()
words2 = sentence2.split()

embeddings_word1 = {word: model.encode([word])[0] for word in words1}
embeddings_word2 = {word: model.encode([word])[0] for word in words2}

# Compare and contrast contextual embeddings
ambiguous_word = "flies"

print(f"Embedding for the word '{ambiguous_word}' in the sentence '{sentence1}':")
print(embeddings_word1[ambiguous_word])
print("\n")

print(f"Embedding for the word '{ambiguous_word}' in the sentence '{sentence2}':")
print(embeddings_word2[ambiguous_word])
print("\n")

# Compute and print the cosine similarity between the embeddings of the ambiguous word
cos_similarity = 1 - cosine(embeddings_word1[ambiguous_word], embeddings_word2[ambiguous_word])
print(f"Cosine similarity between '{ambiguous_word}' in the two sentences: {cos_similarity}")


Embedding for the word 'flies' in the sentence 'She catches flies using a net.':
[ 2.53405929e-01  3.36778253e-01 -2.70037264e-01  5.39220385e-02
 -2.33539507e-01 -2.54001379e-01  3.59673887e-01  1.86390672e-02
  1.62150174e-01 -4.71270293e-01 -3.93633544e-02  1.28598332e-01
 -1.42539188e-01 -1.26482308e-01 -2.87324727e-01 -6.35174140e-02
 -1.67561159e-01  1.49369547e-02  1.79690525e-01  2.25996614e-01
  2.65458226e-01 -2.25750357e-03  1.63663641e-01 -2.53333002e-01
  1.41570017e-01  1.80060882e-02 -2.78067291e-01 -1.47373483e-01
 -4.75895315e-01 -7.36652017e-02 -3.38215590e-01  1.80703878e-01
  2.01729655e-01  5.90272248e-01 -1.40270948e-01 -2.19252750e-01
  9.01221260e-02 -7.40381107e-02  2.44931933e-02 -2.41790056e-01
 -5.27547300e-02 -2.02564001e-02  1.03996240e-01 -2.55665392e-01
 -1.20316111e-01 -2.07057893e-02 -2.48729765e-01  3.14019360e-02
 -2.77894974e-01  8.78127217e-02 -3.31596285e-01  1.13159440e-01
  1.37954175e-01  2.41006002e-01  3.72494273e-02  4.87302542e-02
  1.52402

Here is the assignment proper

In [7]:
from scipy.spatial.distance import cosine
from transformers import BertTokenizer, BertModel
import torch

# Initialize the BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_embedding(sentence):
    # Tokenize the sentence and convert tokens to token IDs
    inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True)

    # Get the output from the BERT model
    with torch.no_grad():
        outputs = model(**inputs)

    # Extract the embeddings for each token
    embeddings = outputs.last_hidden_state[0].numpy()

    return embeddings

# Define the sentences
sentence1 = "time flies like an arrow"
sentence2 = "fruit flies like a banana"

# Get embeddings for tokens in each sentence
embeddings1 = get_embedding(sentence1)
embeddings2 = get_embedding(sentence2)

# Convert the tokens to IDs for both sentences
input_ids1 = tokenizer.encode(sentence1, add_special_tokens=True)
input_ids2 = tokenizer.encode(sentence2, add_special_tokens=True)

# Locate the index of the token "like" in the tokenized sentences
index_like = input_ids1.index(tokenizer.convert_tokens_to_ids("like"))

# Extract embeddings for the token "like" from both sentences using the identified index
embedding_like_1 = embeddings1[index_like]
embedding_like_2 = embeddings2[index_like]

# Compute cosine similarity between the embeddings
cos_similarity = 1 - cosine(embedding_like_1, embedding_like_2)

print(f"Cosine similarity for the token 'like' between the two sentences: {cos_similarity}")


Cosine similarity for the token 'like' between the two sentences: 0.7066124081611633
